[CI] Pinned Rake to version 10.x to prevent clashes with the Yard gem
The builds have been failing on Travis with:

      cd /home/travis/build/elastic/elasticsearch-rails/elasticsearch-model && unset BUNDLE_GEMFILE && bundle exec rake test:unit
      rm -rf tmp/reports
      rake aborted!
      NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000000a9c478>
      /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/yard-0.8.7.6/lib/yard/rake/yardoc_task.rb:69:in `define'

Related: #538